# Generated by Django 3.2.9 on 2021-12-03 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('MR', 'Movie Review'), ('EW', 'Essay Writing'), ('TW', 'Thesis Writing'), ('DW', 'Dissertation Writing'), ('AW', 'Assignment Writing'), ('PS', 'Personal Statement'), ('CSW', 'Case Study Writing'), ('CPW', 'Capstone Project Writing'), ('SW', 'Speech Writing'), ('LRW', 'Lab Report Writing')], max_length=100)),
                ('academic_level', models.CharField(choices=[('HS', 'High School'), ('CL', 'College'), ('UG', 'Undergraduate'), ('PM', 'PostGraduate-Masters'), ('PPH', 'PostGraduate-Phd')], max_length=300)),
                ('pages', models.PositiveIntegerField()),
                ('word_count', models.PositiveIntegerField()),
                ('additional_files', models.FileField(blank=True, null=True, upload_to='media')),
                ('images', models.FileField(blank=True, null=True, upload_to='media')),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='subject',
            field=models.ManyToManyField(to='general.Task'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
